###register auth request
POST http://localhost:3500/auth/register 

content-type: application/json

{
    username:"",
    email: "",
    mobile:"",
    password:"",
    confirm_password:""
}